### ISSUE TITLE
模板没配置package.json,omi-cli无法编译

### ISSUE THREAD

**Issue by bili-jing** [omijs/template-x#1]
![image](https://user-images.githubusercontent.com/45563478/115125051-51eb1a00-9ff8-11eb-8845-1b8aa1b8fbb5.png)
执行 'npx omi-cli init-x my-app' 以后，进入项目npm start 无package.json配置

**Comment by dntzhang** [comment]
这是小程序模板，不需要 npm start

**Comment by bili-jing** [comment]
好的 谢谢

**Comment by bili-jing** [comment]
![image](https://user-images.githubusercontent.com/45563478/115854586-fd62f700-a45c-11eb-930c-af95d0e23557.png)
大佬，我这边是让我npm start的。
如果我想要cli 帮我打包npm依赖，以此来缩小最终打包体积。cli可有提供这种方式呢。
